### PR TITLE
somacore 1.0.6

### PR DESCRIPTION
**Pull request by johnkerl**
Blocks https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/65 which in turn blocks https://github.com/single-cell-data/TileDB-SOMA/pull/1943

### CODE REVIEW

**Comment by thetorpedodog** [comment]
This probably also needs the addition of whatever Conda package provides `pyarrow_hotfix`.

**Comment by johnkerl** [comment]
https://anaconda.org/tiledb/somacore/labels

**Review by thetorpedodog — APPROVED** [review]

**Comment by jdblischak** [comment]
> https://anaconda.org/tiledb/somacore/labels

@johnkerl for context, the binary was already built and uploaded from this [run](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=36962&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) on your internal branch. The typical workflow for a conda-forge feedstock is to submit PRs from a fork, because by default any branch can upload. If you prefer using internal branches, we should limit the uploads to main, as we already do in tiledbsoma-feedstock: https://github.com/TileDB-Inc/tiledbsoma-feedstock/blob/4175b10522b7f6e1ac8687b9ab729224b85896a4/conda-forge.yml#L10

Fortunately your early commits failed to build, otherwise the first one would have been uploaded (without the hotfix), and then the final merged version wouldn't have been uploaded (because the build number hadn't changed since the last upload from your branch). I can send a quick PR

**Comment by johnkerl** [comment]
> I can send a quick PR

@jdblischak yes I would appreciate that 🙏 

It sounds like this repo is broken in a way that I didn't realize, and which is dangerous, and we definitely need it non-broken in the way that `tiledbsoma-feedstock` is.

**Pull request merged**
